# Generated by Django 5.1.4 on 2025-01-06 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_score_to_pass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('answer_text', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('user', 'quiz')},
        ),
    ]
