# Generated by Django 5.1.4 on 2024-12-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['order'], 'verbose_name_plural': 'Quizes'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
