# Generated by Django 5.1.4 on 2025-01-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quiz_options_remove_quiz_number_of_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='requires_payment',
            field=models.BooleanField(default=False),
        ),
    ]
