# Generated by Django 4.2 on 2025-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tcn_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
