# Generated by Django 5.1.4 on 2025-01-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_qualified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tcn_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
