# Generated by Django 5.1.4 on 2025-01-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_user_tcn_number'),
        ('admin_dashboard', '0002_user_is_qualified_alter_user_tcn_number'),
    ]

    operations = [
    ]
