# Generated by Django 5.1.4 on 2025-01-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_merge_20250106_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_quit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='tcn_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
