# Generated by Django 5.1.4 on 2024-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
