# Generated by Django 5.1.4 on 2024-12-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
