# Generated by Django 5.1.4 on 2024-12-28 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_amount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits and contain only numbers.', regex='^\\d{10}$')]),
        ),
    ]
