# Generated by Django 5.1.4 on 2025-01-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
